using System;

namespace Concepts.LINQ
{
    // ==========================================
    // Topic: Anonymous Types
    // ==========================================
    //
    // STORY LINE:
    // THE TEMPORARY ID BADGE:
    // Imagine you are organizing a quick meetup.
    // You don't want to print official, laminated ID cards (Classes) for everyone.
    // It takes too long to design the card, send it to the printer, etc.
    //
    // Instead, you grab a sticky label, write "Name: Bob, Role: Guest" on it, and stick it on their shirt.
    // It works perfectly for the duration of the party.
    // Once the party (Scope) is over, the label is thrown away.
    // You can't use that label at the bank or the airport. It's only valid here and now.
    //
    // ------------------------------------------
    // WHAT IS IT?
    // Anonymous types allow you to create an object with a set of read-only properties without having to explicitly define a class first.
    // The type name is generated by the compiler and is not available to you (hence "anonymous").
    //
    // ------------------------------------------
    // WHY IS IT NEEDED?
    // - Perfect for LINQ queries (Select clauses) where you just need to shape data temporarily.
    // - Reduces boilerplate code when you don't need a reusable class.
    //
    // ==========================================

    class AnonymousTypes
    {
        // To run this file: dotnet run --property:StartupObject=Concepts.AdvancedConcepts.AnonymousTypes
        public static void Main(string[] args)
        {
            Console.WriteLine("--- Anonymous Types Demo ---"); // Output: --- Anonymous Types Demo ---

            // 1. Creating an Anonymous Type
            // We use 'var' because the type has no name we can speak!
            var guest = new { Name = "Bob", Role = "Guest", Age = 25 };

            Console.WriteLine("\n1. The Guest:"); // Output: \n1. The Guest:
            Console.WriteLine($"Name: {guest.Name}"); // Output: Name: Bob
            Console.WriteLine($"Role: {guest.Role}"); // Output: Role: Guest
            // guest.Role = "Admin"; // Error! Properties are Read-Only.

            Console.WriteLine($"Type Name (Generated by Compiler): {guest.GetType().Name}"); // Output: Type Name (Generated by Compiler): <>f__AnonymousType0`3

            // 2. Nested Anonymous Types
            var order = new 
            { 
                OrderId = 101, 
                Customer = new { Name = "Alice", City = "New York" },
                Items = new[] { "Laptop", "Mouse" }
            };

            Console.WriteLine("\n2. Nested Data:"); // Output: \n2. Nested Data:
            Console.WriteLine($"Order {order.OrderId} for {order.Customer.Name} from {order.Customer.City}"); // Output: Order 101 for Alice from New York

            // 3. Use Case: LINQ Projections
            // Imagine we have a list of heavy 'Product' objects, but we only need names and prices.
            var products = new[]
            {
                new Product("Laptop", 1000, "Electronics", 50),
                new Product("T-Shirt", 20, "Clothing", 100),
                new Product("Apple", 1, "Food", 500)
            };

            Console.WriteLine("\n3. LINQ Projection (The most common use):"); // Output: \n3. LINQ Projection (The most common use):
            
            // We create a NEW anonymous type on the fly containing only what we need.
            var cheapItems = products
                .Where(p => p.Price < 100)
                .Select(p => new { p.Name, p.Price }); // "Projection"

            foreach (var item in cheapItems)
            {
                Console.WriteLine($"Item: {item.Name} costs ${item.Price}"); // Output: Item: T-Shirt costs $20
            }
        }
    }

    // Helper class for the demo
    class Product
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Category { get; set; }
        public int Stock { get; set; }

        public Product(string name, decimal price, string category, int stock)
        {
            Name = name;
            Price = price;
            Category = category;
            Stock = stock;
        }
    }
}
